### ISSUE TITLE
Auto disabled

### ISSUE THREAD

**Issue by jj94523** [LeonBlade/BDTHPlugin#1]
Hi I've been using your mod for a while, and love it. Thanks for making it. The XIV launcher updated and since the update. Every time I try to us the mod it say the command does not exist. I removed the files and reinstalled with a fresh download and nothing. When I checked the install folder I found a file that seems the launcher is adding. This happens every time I launch. Any help would be appreciated https://imgur.com/a/WTIbdHU

**Comment by LeonBlade** [comment]
Just remove the `.disabled` file, you may also need to change `DalamudApiVersion` in the JSON file from 1 to 2.

**Comment by jj94523** [comment]
I guess I wasn't clear. I've deleted the file multiple times and the launcher puts it back every single time. I'll try the json fix though

**Comment by jj94523** [comment]
json change fixed it. Thanks!
