### ISSUE TITLE
Not availaible in /xlplugins

### ISSUE THREAD

**Issue by sioc-de-narf** [LeonBlade/BDTHPlugin#10]
Hi,
i installed the new XIVLauncher, if i follow again your how-to : https://github.com/LeonBlade/DalamudPlugins

once added, your plugin can't be find by the search way and is not shown in the list.

I tried to install it manually and it crashed FF14.

I attached the popup error :

![crashBDTH](https://user-images.githubusercontent.com/14063185/114748928-aec5a680-9d52-11eb-8187-ac3570dfd7b8.png)

PS: I had the same error after the XIVLauncher updates.

**Comment by sioc-de-narf** [comment]
I just seen the update to 1.2.8

BUT the https://raw.githubusercontent.com/LeonBlade/DalamudPlugins/main/repo.json

is still at 1.2.7

**Comment by LeonBlade** [comment]
Should be working fine now, multiple users have reported it works fine.

**Comment by Lanselotto** [comment]
it seems to be a conflict between XIVLauncher, Dalamud in particular, and other program with injection like Gshade. U need to set XIVLauncher plugin loadin delay to 2500 millisecond
