### ISSUE TITLE
[Suggestion] Decoration save/load

### ISSUE THREAD

**Issue by sadtaco** [LeonBlade/BDTHPlugin#18]
Sorry if you don't take suggestions, but there was no templates to chose from for issues.

I know it'd be difficult to implement, but I'd like to suggest a save and load for decorations where saving would save the list of items and their position and rotations, and loading would attempt to place those items from storage and restore them to those given positions for each one.

It's a shame that this isn't built into relocation in the game already and even needs a plugin for it.

**Comment by LeonBlade** [comment]
Hey, suggestions are fine. However, the plug-in HousingPos already does
this.
