### ISSUE TITLE
Gizmo doesn't appear

### ISSUE THREAD

**Issue by bobbahbrown** [LeonBlade/BDTHPlugin#26]
Hello,

Just installed the plugin for the first time. Gizmo doesn't appear with appropriate gizmo setting enabled and selecting furniture with the rotate tool. Friend who is a long-time user reports that the gizmo is not appearing for him as well now after restarting.

Possibly broke from a Dalamud update?

![image](https://user-images.githubusercontent.com/10467687/149341961-ae34df54-befc-41c3-8a3a-bad4be126c2b.png)

**Comment by LeonBlade** [comment]
Do you happen to both have multiple monitors?

**Comment by bobbahbrown** [comment]
We both have multi monitors, and oddly enough when logging in and checking today mine appears to be working as well as my friends.

Super strange!

**Comment by BlackBurnJim** [comment]
I am also having this issue with the gizmo not appearing consistently, and I am using multiple monitors. Is there something I need to change to have it work? I didn't have any problem until recently. (One or two Dalamud updates ago)

**Comment by blountra** [comment]
I have a dual monitor setup and i have dual monitors turned off in the Dalamud settings but i'm still not getting any gizmo option or the ability to float objects in housing

**Comment by blountra** [comment]
![Screenshot 2022-03-06 154802](https://user-images.githubusercontent.com/101073186/156954306-7417e4ac-ebfc-4e6c-9697-90ebd95d3f67.png)

here is what my settings look like still no gizmo options even with it selected

**Comment by LeonBlade** [comment]
You’re not in rotate mode.

**Comment by blountra** [comment]
> You’re not in rotate mode.
> […](#)

Omg yes thank you! That was it!
