### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by thoggx** [LeonBlade/BDTHPlugin#27]
There used to be a bug/feature if you were typing into/highlighting the x y or z coordinate and then clicked another object it would overwrite the clicked objects x y or z coordinate with the highlighted one. I used to use that feature all the time to very quickly send objects like walls and stuff to the same axis to speed up lining things up. Could you readd that as a feature? Maybe holding shift or alt or something while clicking an object and having a coordinate highlighted causes it to copy the value to the alt clicked object?

**Comment by LeonBlade** [comment]
A locking system has been added to the plugin to mimic this behavior.
