### ISSUE TITLE
Gizmo can be lost until plugin restart due to objects zooming off to infinity

### ISSUE THREAD

**Issue by ark-royal-91** [LeonBlade/BDTHPlugin#29]
While moving objects along the axis parallel to the camera's line of sight, it's possible for objects to rapidly move to arbitrarily high distances, including, on occasion, distances recorded as infinity. If this occurs, even if no actual object movement happens (such as while moving a wall object with place anywhere and canceling out of the motion), the gizmo will no longer appear when any objects are selected until the plugin is restarted.

(Apologies for a lack of video - I've only had this issue happen a couple times and have not been able to reliably replicate it on command.)

**Comment by LeonBlade** [comment]
This is a known issue, I don't think I can really do anything about it as I did not create the gizmo itself, it's part of a library integrated with ImGui with Dalamud.
