### ISSUE TITLE
Chairs un useable 

### ISSUE THREAD

**Issue by BaronSolace** [LeonBlade/BDTHPlugin#3]
Placing chairs while "place anywhere" enabled or open makes chairs un useable as a seat.  this is a recent thing since the new patch went live.    toggling it off and moving the chair via normal methods makes the seat useable,  but then you lose the easy ability to float it and function.   i can submit a gif or stream to you directly if need be.

**Comment by LeonBlade** [comment]
I cannot replicate this. I just pulled out a stool with place anywhere, floated it in the air, and was able to sit on it just fine. I'd be happy to take a look at whatever you can show to help fix this issue.

**Comment by LeonBlade** [comment]
Resolved as a strange quirk and not a bug of software.
