### ISSUE TITLE
Trouble with lofts

### ISSUE THREAD

**Issue by michelledietz** [LeonBlade/BDTHPlugin#31]
Good morning!  Thank you so much for this plugin.  I have loved using it in the past and was so excited to see it back this morning.  

As of right now, I am unable to place anything on lofts, even with "place anywhere" checked.  I am making sure the item is outlined in gold/orange instead of purple before placing and have tried using both the place and rotate functions to no avail.  Every time it says "unable to place item."  

I have tried to uninstall and reinstall the plugin, restart my game, and restart my computer but all of those didn't fix it.  Any ideas of what I can try?  Thanks in advance for any help you can give me!  Got a house finally just before patch and looking to make it swanky by using this.

**Comment by LeonBlade** [comment]
I forgot to check some of that stuff, I’ll look later today.

**Comment by ausgezeichnet15** [comment]
Appreciate it!

**Comment by LeonBlade** [comment]
I looked into this any I don't have this issue. Could you create a recording or something showing this error?
