### ISSUE TITLE
Crash using the Plugin.

### ISSUE THREAD

**Issue by Phleks** [LeonBlade/BDTHPlugin#32]
First, thanks for the Plugin at all.

Since the last Patch I experience game crashes when using the Plugin (and I only use this plugin I disabled all the others.)
Also while Switching into the Menu to place items the game freezes for short time. 
I'm not sure what might cause this problems, I also can't see anything in the Dalamud logs.

**Comment by LeonBlade** [comment]
Can you try to reinstall the plugin? I haven't heard any other reports of issues.

**Comment by Phleks** [comment]
Reinstalling Dalamud helped. SO don't know what went Wrong on Dalamuds side.
Sorry for the Ticket.
