### ISSUE TITLE
unable to resize plugin window

### ISSUE THREAD

**Issue by theabhishek2511** [LeonBlade/BDTHPlugin#33]
The plugin window is fixed to a size, and i am unable to resize it. Certain options end up being cut off.

![image](https://user-images.githubusercontent.com/2082634/164970364-69f262fd-4b38-43ff-8567-c33aabf43a84.png)

**Comment by ladybunne** [comment]
Same issue here, it doesn't play nice with Dalamud's text scaling options.
![image](https://user-images.githubusercontent.com/4102334/168699644-00d27901-96f2-4d91-998e-d8da648c9669.png)
