### ISSUE TITLE
Since last patch

### ISSUE THREAD

**Issue by dahxic** [LeonBlade/BDTHPlugin#35]
I've noticed an odd issue since last patch. I can recreate this consistently.  If I install BDTH it works fine until I exit the game and relaunch.   Logging off and on is fine but closing the game and relaunching causes BDTH to no longer work properly.  If I go into rotation mode and click on an item all values are Zero.  If I hover over a value the ingame item will immediately teleport to 0,0,0 in my house.   I hope you have an idea as to whats causing this. hah

**Comment by LeonBlade** [comment]
Likely related to #36, closing. Please comment if you feel this isn't correct and you still have this issue after the latest update.
