### ISSUE TITLE
housing items keep snapping back

### ISSUE THREAD

**Issue by PeachyTristan** [LeonBlade/BDTHPlugin#37]
anytime I try to move something up or down it doesn't stay where I placed it, and it will just keep snapping back to the floor. I have tried redownloading the plugin, reset and reload in settings, and don't have any other housing plugins! Haven't ever run into this issue before until the last couple days! Not sure if there's something maybe I'm missing?

**Comment by LeonBlade** [comment]
Can you please provide a clip of what you're experiencing so I can better understand what's happening?
