### ISSUE TITLE
Floating objects too close to floor causes them to snap to floor. 

### ISSUE THREAD

**Issue by Lightningcount** [LeonBlade/BDTHPlugin#39]
Trying to float several objects. Running into issues where if the item is too close to the floor, it will snap back to the floor. Tried uninstalling and reinstalling the app/plugin to no avail. I have ffxiv on my laptop and it never had the app before. I went ahead and installed the app on it and the plugin. Still getting the issue. Trying to float several items on a stage to make a raised platform but it keeps snapping back to the floor unless we float them at comically high levels.

**Comment by LeonBlade** [comment]
This is a limitation of the engine. Nothing I can do about it. If things are too close to the floor, they will snap to the floor.
