### ISSUE TITLE
UI glitch

### ISSUE THREAD

**Issue by NevendyND** [LeonBlade/BDTHPlugin#40]
I think its the same Issue as here
https://github.com/karashiiro/SoundSetter/issues/21

more is here: https://github.com/goatcorp/FFXIVQuickLauncher/issues/1134

![jftjftj](https://user-images.githubusercontent.com/28860034/190878860-4c33d507-0393-4c6e-8e87-7919018a076b.PNG)

**Comment by LeonBlade** [comment]
Thanks, I'll fix it soon.
