### ISSUE TITLE
Game sometimes crashes when entering furnishing mode

### ISSUE THREAD

**Issue by retep998** [LeonBlade/BDTHPlugin#42]
I haven't been able to determine the cause, and it only sometimes happens. It *feels* like it happens more when the game has been running for a while, whereas after a fresh game start it works fine, but I haven't properly tested that theory.

**Comment by MistrxxGoat** [comment]
Same thing happening to me. happened twice just today .

**Comment by Lynesth** [comment]
I confirm this happens as well.

**Comment by iamedd** [comment]
This definitely happened to me every time after using DC travel to go to another DC, then returning back to my home DC/world, entering a house and going into furnishing mode would consistently end in a hard crash.

**Comment by LeonBlade** [comment]
Without any way to replicate the issue, I cannot address this. If you can reproduce this consistently, please open a new ticket.
