### ISSUE TITLE
Plugin causes Dalamud crash when closing game

### ISSUE THREAD

**Issue by Piratecatte** [LeonBlade/BDTHPlugin#43]
This is a recent bug. After disabling all 3rd party plugins per the guidance of GOAT place and going through them one at a time only BDTH caused a crash. All of the others, alone or on together, did not produce the crash. This my first time using Github outside of getting a file so forgive if I'm not following the right procedures here. I've attached the files in a zip file from the crash notice though I do not know if they will help.
[Dalamud.zip](https://github.com/LeonBlade/BDTHPlugin/files/10231517/Dalamud.zip)

**Comment by LeonBlade** [comment]
I will look into this soon, thank you for creating this issue.

**Comment by LeonBlade** [comment]
As this is an old issue, I'm closing this. If you still have issues, please let me know. Sorry I never had time to look at it directly.
