### ISSUE TITLE
Interface no longer visible

### ISSUE THREAD

**Issue by Sophie-moonway** [LeonBlade/BDTHPlugin#44]
interface is no longer visible after changing the screen resolution, the interface where you can set the setting or the accuracy of the objects is no longer visible. You can only move the objects with the arrows. I have tried everything from resetting to installing the plugin and fixing the launcher, but nothing has helped. Please help

**Comment by LeonBlade** [comment]
Use the command `/bdth reset`

**Comment by Sophie-moonway** [comment]
Super has helped many thanks goes again :)
