### ISSUE TITLE
Crash using keyboard

### ISSUE THREAD

**Issue by Lynesth** [LeonBlade/BDTHPlugin#46]
I'm using an AZERTY keyboard.

If, while in furnishing mode, I try using `Shift` + `&` (or `é`, `"`, etc) which is used to write down numbers the game instantly crashes, no log or anything. I have to use the numpad at all time.

I believe this is linked to the fact that using `Shift` + one of those keys also changes the tool (Move, Rotate, Store, etc).

No issue with QWERTY keyboard, but probably because `Shift` + `1` doesn't try to both input a number and change the tool.

**Comment by LeonBlade** [comment]
If you can provide logs for this I can try to look into a fix.

**Comment by Sevii77** [comment]
Mode keybinds are a feature of [Better Housing](https://github.com/Sevii77/properhousing), not BDTH and has been fixed since [136e402](https://github.com/Sevii77/properhousing/commit/136e4021d6601fe5b45d0e0c581fdd10e9f1d881)
