### ISSUE TITLE
Not working with FF14 Patch 6.3

### ISSUE THREAD

**Issue by sioc-de-narf** [LeonBlade/BDTHPlugin#48]
Not working with FF14 Patch 6.3 update needed

**Comment by QK777** [comment]
Will it work if I load the DLL using "Path" under "experimental dev settings"?

**Comment by owopeachy** [comment]
Thanks so much, should hold me over till the real one comes out

**Comment by BrynDus** [comment]
A little new to this, where might I find/navigate to the .dll?

**Comment by BellaVXoXo** [comment]
Shoutout to Gedway to actually being proactive and communicating with the community while providing a fix. The creator has been sitting on overwatch 2 all weekend and locked the discord when he was getting praised. I saw folks send money over as a thank you and it’s still not updated.

**Comment by chirpxiv** [comment]
PR #50 covers everything needed for patch 6.3. Please refrain from using unofficial repos in the mean time, builds from untrusted sources can come bundled with malicious code.
