### ISSUE TITLE
Locale-dependent parsing

### ISSUE THREAD

**Issue by Ottermandias** [LeonBlade/BDTHPlugin#5]
The new command parses its floats locale-dependent, i.e. on my German system with ',' as the decimal separator ( 2.8 -> 28 and 2,8 -> 2.8).
The GUI displays its float in us-locale with '.' as decimal separator, though.

Nothing terrible, just noticed it. :)

**Comment by LeonBlade** [comment]
Thanks, I'll fix this soon!
