### ISSUE TITLE
No BDTH Window?

### ISSUE THREAD

**Issue by NerdVania** [LeonBlade/BDTHPlugin#54]
I can type in /bdth and nothing pops up. Its nowhere on my screen.
Ive tried restarting. Ive tried disabling/re-enabling.
I have tried removing it from plugins all together.
I cant get the box to pop up.
Any Ideas?

I was using it about an hour ago and it worked fine. I stepped outside the house then went back in (To change doors outside) and thats when it started messing up.

**Comment by LeonBlade** [comment]
Please use `/bdth reset`
