### ISSUE TITLE
Window does not populate

### ISSUE THREAD

**Issue by Pipadee** [LeonBlade/BDTHPlugin#59]
The main bdth window is not showing up. When I am in rotation mode, I get the ability to move things as usual, but the gizmo settings and the fine-tuning isn't there. It might be a super simple fix, i'm not sure. I'm not sure if its a bug of some sort, but I wanted to find out either way :). Thank you very much for all you do!
![help finding window](https://github.com/LeonBlade/BDTHPlugin/assets/149895007/d2bf89f2-80d8-47ed-b8d2-17718ea8e7fe)

**Comment by LeonBlade** [comment]
Hello, please try to use the command `/bdth reset`.

**Comment by Pipadee** [comment]
Fantastic!  That did it!  tysm. I'll keep checking the discord as well for joining. Leon you're wonderful!
