### ISSUE TITLE
plugin tab missing

### ISSUE THREAD

**Issue by sleepycvampire** [LeonBlade/BDTHPlugin#61]
hello so I stupidly dragged the tab off of my screen when I was moving an item. I tried uninstalling and reinstalling, quitting my game, reinstalling it entirely from the experimental tab as well and still it is no where to be seen. Typing the /bdth as well doesn't work for me as it doesn't re appear anywhere and is still off my screen. I'm not great with computer stuff so looking for help thank you

**Comment by LeonBlade** [comment]
This will be fixed when I get around to pushing the fix, but for now just use `/bdth reset`
