### ISSUE TITLE
7.0 Update?

### ISSUE THREAD

**Issue by overnightsiren** [LeonBlade/BDTHPlugin#63]
Hello! Just wondering if this plugin is planned to be updated for 7.0 now that Dalamud has been updated?

**Comment by jkw26** [comment]
From the discord, "Regarding BDTH, it will be updated when Leon can update it. Before anything, let Leon enjoy the game first, beyond that, he has to wait for Dalamud to be available for plugin testing. DO NOT harass Leon about updating BDTH, you will be notified when there is an update available."

**Comment by jackandcarter** [comment]
asking when there will be an update isn't harassment fyi. Also Malamud has been available for plugin testing for quite a while now, and has been officially updated as of today, so asking the question is legitimately justified.

As far as updating it, I would be more than happy to help out if it's needed or would help to get this out faster with no issues. There are also other mods that can do the same thing BDTH does in the meantime. However, I'm loyal to this mod as it has been the most light weight and handy one for housing so far. Keep up the good work!

**Comment by LeonBlade** [comment]
Thanks everyone for your passion for this tool. I'm glad there are so many of you who are eager to use it again in the new expansion. I will be updating it for 7.0 soon.

Life has been a little rough for me lately, so my priorities haven't been focused on this plugin.

Thank you again for using my plugin!

**Comment by djxulfudd** [comment]
this is by far my fav and pretty much the only plugin i use! ty kindly for your hard work @LeonBlade

**Comment by LarsenEndeavors** [comment]
It's times like these I wish I knew how to contribute here, been a dev for a long time, need to get into the community.

**Comment by LeonBlade** [comment]
I think I misplaced my Ghidra project or something, but thankfully I have a slightly older client so I should be able to get things working shortly. I updated the codebase to work with version 10 of the Dalamud API, just need to update the offsets now.

@LarsenEndeavors There's so many things to learn as a developer. I'm constantly wondering what I should spend time on learning and whatnot. Just take it at your own pace!

**Comment by overnightsiren** [comment]
This is the first plugin I've ever used that's not native to Dalamud. Once the update is out, will I have to reinstall it?

**Comment by Lillyloves23** [comment]
Leon do you have a kofi or something?

**Comment by LeonBlade** [comment]
Quick update! The plugin is mostly working on my end, but the gizmo has some strange issues I can't seem to work out. I'll continue to look into the problem. Thank you for your patience.

> Leon do you have a kofi or something?

Yes, I do in fact. No one is obligated to support me, but I'm always very grateful to those that do.

[https://ko-fi.com/leonblade](https://ko-fi.com/leonblade)

**Comment by LarsenEndeavors** [comment]
@LeonBlade I'm finally getting into non-corporate software development and getting into the open-source and game development communities, I'll do some research but if you ever need a spare set of hands (as I'm sure you've been told a thousand times) I'm more than happy to donate development time, to you or Otter.

**Comment by FishStyx001** [comment]
this plugin is the only one I use and its saved me tons of trouble with having to do "fix up" designs with needy/impatient contractors, as the rest of the community has voiced this is a top knotch plugin and as you mentioned other priorities have taken precedence over updating, all the best in your daily balance and looking forward to the next iteration of this plugin. in the meanwhile time to decorate old school with the wooden slat partition and trusty ancient shelf.

**Comment by jackandcarter** [comment]
> @LeonBlade I'm finally getting into non-corporate software development and getting into the open-source and game development communities, I'll do some research but if you ever need a spare set of hands (as I'm sure you've been told a thousand times) I'm more than happy to donate development time, to you or Otter.

I second this, I have an extensive dev background with major companies, but no more, no more corporations for me. I want to be part of a real dev community, no more limits. I'd be more than happy to help code anything. Been getting some pretty good ideas after looking at the APIs.

**Comment by LarsenEndeavors** [comment]
> > @LeonBlade I'm finally getting into non-corporate software development and getting into the open-source and game development communities, I'll do some research but if you ever need a spare set of hands (as I'm sure you've been told a thousand times) I'm more than happy to donate development time, to you or Otter.
> 
> I second this, I have an extensive dev background with major companies, but no more, no more corporations for me. I want to be part of a real dev community, no more limits. I'd be more than happy to help code anything. Been getting some pretty good ideas after looking at the APIs.

BROTHER!
