### ISSUE TITLE
Failed to install plugin.

### ISSUE THREAD

**Issue by SkylarDragon** [LeonBlade/BDTHPlugin#64]
Trying to install BDTH will bring up an Installer Error, and the plugin will say load error. I tried deleting and reinstalling a few times, but I get the same error. There's not much error info other than "load error" and to just contact the plugin author, so I figured I'd open an issue here. I attached a couple images of the error, even if it's not too much help.
![image](https://github.com/LeonBlade/BDTHPlugin/assets/10256423/795a7cb5-0edb-4324-b845-81396edb78b3)
![image](https://github.com/LeonBlade/BDTHPlugin/assets/10256423/0c9ce040-4334-4bae-b3d3-43f7ff065e0b)

**Comment by soisauceee** [comment]
It's not ready yet, more info can be found here :)

https://github.com/LeonBlade/BDTHPlugin/issues/63

**Comment by SkylarDragon** [comment]
i thought it was ready because its been marked as not compatible till today, its also a fresh install since my computer decided to die during the 48 hour maintenance lol

**Comment by LeonBlade** [comment]
Hi! Sorry about that, I pushed some of the fixes up so someone else could look at them to help me solve some remaining issues. This may have affected the update in this way. Sorry for the confusion, but it's not quite ready yet. Thank you for your patience.
