### ISSUE TITLE
XYZ coords

### ISSUE THREAD

**Issue by Tenikins** [LeonBlade/BDTHPlugin#69]
I'm having an issue where the Z coord movement arrow on the gizmo is ... snapping.

snapping is not enabled on /bdth interface for me. I have enabled, and disabled it, and objects are still snapping. No free movement like there is with X and Y coords arrows on the gizmo.

**Comment by LarsenEndeavors** [comment]
Came here to bring this, can confirm.

**Comment by Rellawing** [comment]
Seconded! I was going to report this myself, but having discovered it's a universal issue, no need!

I wanted to say also, "Thank you so much for rolling out an update for us! Even with a glitch, I'm extremely happy! It's something that can be worked around, short term, so I'm nothing but pleased!

**Comment by Loucka88** [comment]
Thank you for Updating!♥

Sadly also +1 on the Z Axis not doing its job at all :<

**Comment by LeonBlade** [comment]
Latest update should fix the issue.

**Comment by Loucka88** [comment]
> Latest update should fix the issue.

Works perfectly again, thank you for such a quick fix!

**Comment by Tenikins** [comment]
Thank you so much for all your hard work and the updates, and the quick update to the Z axis problem.  Have a fantastic day.
