### ISSUE TITLE
Does not work with outdoor items. 

### ISSUE THREAD

**Issue by Lightningcount** [LeonBlade/BDTHPlugin#8]
I am in rotate mode and the position editor does not come up. I go inside the house and it works fine. 
![image](https://user-images.githubusercontent.com/15706216/107960226-fb1a8300-6f69-11eb-85c8-7d64c22ef8df.png)

![image](https://user-images.githubusercontent.com/15706216/107960372-2ac98b00-6f6a-11eb-9de5-91e1e79ff4dc.png)

**Comment by LeonBlade** [comment]
Outdoor is disabled because of abuse.
