### ISSUE TITLE
no longer working outside

### ISSUE THREAD

**Issue by BaronSolace** [LeonBlade/BDTHPlugin#9]
whole menu is greyed out and cant freely move around items anymore  outdoor housing only

**Comment by LeonBlade** [comment]
It’s intentional, I may allow it to work again with limitations in the
future. People were floating things into the sky and causing problems.

**Comment by BaronSolace** [comment]
AH.  ic.   that sucks, people always ruin a good thing.  i hope yo do bring it back in some form though

**Comment by LeonBlade** [comment]
The latest version lets you use the coordinates, but restricts the Y coordinate.
